on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

# >>>>> Build / Cache the apphost binaries <<<<<
  check-apphost-cache:
    name: Check apphost binary cache

    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache-check.outputs.cache-hit }}
      cache-key: ${{ steps.cache-check.outputs.cache-primary-key }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache/restore@v3
        id: cache-check
        with:
          key: apphost-binaries-${{ hashFiles('apphost') }}
          lookup-only: true

  build-apphost:
    name: Build apphost binaries

    needs: check-apphost-cache
    uses: ./.github/workflows/build-apphost.yml
    if: ${{ !needs.check-apphost-cache.cache-hit }}

  cache-apphost-binaries:
    name: Cache built apphost binaries

    runs-on: ubuntu-latest
    needs: [check-apphost-cache, build-apphost]
    if: ${{ !needs.check-apphost-cache.cache-hit }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: apphost-binaries
          path: apphost
      - uses: actions/cache/save@v3
        id: cache-check
        with:
          key: ${{ needs.check-apphost-cache.cache-key }}
          path: apphost

# >>>>> Build the nuget package <<<<<
  build-nugetpkg:
    runs-on: ubuntu-latest
    needs: build-apphost
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

        # Build / Cache the MSBuild tasks assembly
      - name: Cache Piton MSBuild tasks assembly
        uses: actions/cache@v4
        id: cache-msbuild-tasks
        with:
          path: |
            msbuild/bin
            msbuild/obj
          key: piton-msbuild-tasks-${{ hashFiles('msbuild') }}
          restore-keys: |
            piton-msbuild-tasks-

      - name: Build Piton MSBuild tasks
        if: steps.cache-msbuild-tasks.outputs.cache-hit != 'true'
        run: dotnet build -c Release -p:TreatWarningsAsErrors=true msbuild

        # Pack the nuget package
      - name: Pack nuget package
        run: dotnet pack -p:TreatWarningsAsErrors=true --output out

      - uses: actions/upload-artifact@v4
        with:
          name: nuget
          if-no-files-found: error
          path: out/*nupkg